version: '3'

services:
  mongodb:
    image: mongo:6.0.6
    ports:
      - "27017:27017"

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
